spring:
  application:
    name: gateway-security
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:80
    gateway:
      discovery:
        locator:
      # 开启网关动态路由
          enabled: true
  main:
    web-application-type: reactive
server:
  port: 10000

my:
  server:
    addr: 150.158.5.120

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
#jwt
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: mySecret
  # JWT的超期限时间(60*60*24)
  expiration: 604800
  tokenHead: Bearer