spring:
  application:
    name: gateway-security
  cloud:
    nacos:
      discovery:
        server-addr: ${my.server.addr}:80
    gateway:
      discovery:
        locator:
      # 开启网关动态路由
          enabled: true
  main:
    web-application-type: reactive
server:
  port: 10000

my:
  server:
    addr: 150.158.5.120